import type { ImageSourcePropType } from "react-native";
// Representative category photography, credited in assets/catalog/credits.json.
const photos: Record<string, ImageSourcePropType> = {
  "camera": require("../../assets/catalog/camera.webp"),
  "webcam": require("../../assets/catalog/webcam.webp"),
  "tripod": require("../../assets/catalog/tripod.webp"),
  "monitor": require("../../assets/catalog/monitor.webp"),
  "tablet": require("../../assets/catalog/tablet.webp"),
  "microphone": require("../../assets/catalog/microphone.webp"),
  "audio-interface": require("../../assets/catalog/audio-interface.webp"),
  "headphones": require("../../assets/catalog/headphones.webp"),
  "speaker": require("../../assets/catalog/speaker.webp"),
  "studio-light": require("../../assets/catalog/studio-light.webp"),
  "keyboard": require("../../assets/catalog/keyboard.webp"),
  "mouse": require("../../assets/catalog/mouse.webp"),
  "cables": require("../../assets/catalog/cables.webp"),
  "workspace": require("../../assets/catalog/workspace.webp"),
  "laptop": require("../../assets/catalog/laptop.webp"),
  "computer": require("../../assets/catalog/computer.webp"),
  "storage": require("../../assets/catalog/storage.webp"),
  "router": require("../../assets/catalog/router.webp"),
  "hub": require("../../assets/catalog/hub.webp"),
  "washing-machine": require("../../assets/catalog/washing-machine.webp"),
  "refrigerator": require("../../assets/catalog/refrigerator.webp"),
  "air-conditioner": require("../../assets/catalog/air-conditioner.webp"),
  "fan": require("../../assets/catalog/fan.webp"),
  "vacuum": require("../../assets/catalog/vacuum.webp"),
  "iron": require("../../assets/catalog/iron.webp"),
  "air-purifier": require("../../assets/catalog/air-purifier.webp"),
  "air-fryer": require("../../assets/catalog/air-fryer.webp"),
  "blender": require("../../assets/catalog/blender.webp"),
  "kettle": require("../../assets/catalog/kettle.webp"),
  "coffee-machine": require("../../assets/catalog/coffee-machine.webp"),
  "cooker": require("../../assets/catalog/cooker.webp"),
  "toaster": require("../../assets/catalog/toaster.webp"),
  "microwave": require("../../assets/catalog/microwave.webp"),
  "security-camera": require("../../assets/catalog/security-camera.webp"),
  "smart-plug": require("../../assets/catalog/smart-plug.webp"),
  "bulb": require("../../assets/catalog/bulb.webp"),
  "smart-lock": require("../../assets/catalog/smart-lock.webp"),
  "smart-home": require("../../assets/catalog/smart-home.webp"),
  "power-bank": require("../../assets/catalog/power-bank.webp"),
  "charger": require("../../assets/catalog/charger.webp"),
  "extension": require("../../assets/catalog/extension.webp"),
  "ups": require("../../assets/catalog/ups.webp"),
  "power-station": require("../../assets/catalog/power-station.webp"),
  "solar-panel": require("../../assets/catalog/solar-panel.webp"),
};
export function catalogPhoto(path: string | null): ImageSourcePropType | undefined {
  const key = path?.match(/^\/images\/catalog\/([a-z-]+)\.webp$/)?.[1];
  return key ? photos[key] : undefined;
}
